import tailwindcssAnimate from 'tailwindcss-animate'
import typography from '@tailwindcss/typography'

/** @type {import('tailwindcss').Config} */
const config = {
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  darkMode: ['selector', '[data-theme="dark"]'],
  plugins: [tailwindcssAnimate, typography],
  prefix: '',
  safelist: [
    'lg:col-span-4',
    'lg:col-span-6',
    'lg:col-span-8',
    'lg:col-span-12',
    'border-border',
    'bg-card',
    'border-error',
    'bg-error/30',
    'border-success',
    'bg-success/30',
    'border-warning',
    'bg-warning/30',
  ],
  theme: {
    container: {
      center: true,
      padding: {
        '2xl': '2rem',
        DEFAULT: '1rem',
        lg: '2rem',
        md: '2rem',
        sm: '1rem',
        xl: '2rem',
      },
      screens: {
        '2xl': '86rem',
        lg: '64rem',
        md: '48rem',
        sm: '40rem',
        xl: '80rem',
      },
    },
    extend: {
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      colors: {
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        background: 'hsl(var(--background))',
        border: 'hsla(var(--border))',
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        foreground: 'hsl(var(--foreground))',
        input: 'hsl(var(--input))',
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        ring: 'hsl(var(--ring))',
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        success: 'hsl(var(--success))',
        error: 'hsl(var(--error))',
        warning: 'hsl(var(--warning))',
      },
      fontFamily: {
        mono: ['var(--font-geist-mono)'],
        sans: ['Open Sans', 'sans-serif'],
        'open-sans': ['Open Sans', 'sans-serif'],
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
      },
      typography: () => ({
        DEFAULT: {
          css: [
            {
              '--tw-prose-body': 'hsl(var(--foreground))',
              '--tw-prose-headings': 'hsl(var(--foreground))',
              '--tw-prose-links': 'hsl(var(--primary))',
              '--tw-prose-bold': 'hsl(var(--foreground))',
              '--tw-prose-counters': 'hsl(var(--muted-foreground))',
              '--tw-prose-bullets': 'hsl(var(--muted-foreground))',
              '--tw-prose-hr': 'hsl(var(--border))',
              '--tw-prose-quotes': 'hsl(var(--foreground))',
              '--tw-prose-quote-borders': 'hsl(var(--border))',
              '--tw-prose-captions': 'hsl(var(--muted-foreground))',
              '--tw-prose-code': 'hsl(var(--foreground))',
              '--tw-prose-pre-code': 'hsl(var(--muted-foreground))',
              '--tw-prose-pre-bg': 'hsl(var(--muted))',
              '--tw-prose-th-borders': 'hsl(var(--border))',
              '--tw-prose-td-borders': 'hsl(var(--border))',
              h1: {
                fontWeight: '300',
                fontSize: '3.75rem',
                lineHeight: '4.4rem',
                marginTop: '0',
                marginBottom: '1rem',
                color: 'hsl(var(--foreground))',
              },
              h2: {
                fontWeight: '300',
                fontSize: '2.813rem',
                lineHeight: '2.25rem',
                marginTop: '2rem',
                marginBottom: '1rem',
                color: 'hsl(var(--foreground))',
              },
              h3: {
                fontWeight: '300',
                fontSize: '2.125rem',
                lineHeight: '2rem',
                marginTop: '1.5rem',
                marginBottom: '0.75rem',
                color: 'hsl(var(--foreground))',
              },
              h4: {
                fontWeight: '300',
                fontSize: '1.25rem',
                lineHeight: '1.75rem',
                marginTop: '1.5rem',
                marginBottom: '0.5rem',
                color: 'hsl(var(--foreground))',
              },
              h5: {
                fontWeight: '300',
                fontSize: '1.75rem',
                lineHeight: '2.75rem',
                color: 'hsl(var(--foreground))',
              },
              h6: {
                fontWeight: '300',
                fontSize: '1.25rem',
                lineHeight: '1.75rem',
                marginTop: '1.5rem',
                marginBottom: '0.5rem',
                color: 'hsl(var(--foreground))',
              },
              p: {
                fontWeight: '400',
                marginTop: '1.25rem',
                marginBottom: '1.25rem',
                lineHeight: '1.75',
                color: 'hsl(var(--foreground))',
              },
              a: {
                color: 'hsl(var(--primary))',
                textDecoration: 'underline',
                textDecorationThickness: '1px',
                textUnderlineOffset: '2px',
                '&:hover': {
                  color: 'hsl(var(--primary))',
                  textDecorationThickness: '2px',
                },
              },
              strong: {
                fontWeight: '600',
                color: 'hsl(var(--foreground))',
              },
              code: {
                color: 'hsl(var(--foreground))',
                backgroundColor: 'hsl(var(--muted))',
                padding: '0.25rem 0.375rem',
                borderRadius: '0.375rem',
                fontSize: '0.875rem',
                fontWeight: '600',
              },
              'code::before': {
                content: '""',
              },
              'code::after': {
                content: '""',
              },
              pre: {
                backgroundColor: 'hsl(var(--muted))',
                borderRadius: '0.5rem',
                padding: '1rem',
                overflow: 'auto',
                fontSize: '0.875rem',
                lineHeight: '1.5',
              },
              'pre code': {
                backgroundColor: 'transparent',
                padding: '0',
                borderRadius: '0',
                fontSize: 'inherit',
                fontWeight: '400',
              },
              blockquote: {
                borderLeftWidth: '4px',
                borderLeftColor: 'hsl(var(--border))',
                paddingLeft: '1rem',
                fontStyle: 'italic',
                color: 'hsl(var(--muted-foreground))',
                margin: '1.5rem 0',
              },
              ul: {
                marginTop: '1.25rem',
                marginBottom: '1.25rem',
                paddingLeft: '1.625rem',
              },
              ol: {
                marginTop: '1.25rem',
                marginBottom: '1.25rem',
                paddingLeft: '1.625rem',
              },
              li: {
                marginTop: '0.5rem',
                marginBottom: '0.5rem',
                lineHeight: '1.75',
              },
              table: {
                width: '100%',
                borderCollapse: 'collapse',
                marginTop: '2rem',
                marginBottom: '2rem',
              },
              'thead th': {
                borderBottomWidth: '1px',
                borderBottomColor: 'hsl(var(--border))',
                paddingBottom: '0.75rem',
                paddingTop: '0.75rem',
                paddingLeft: '0',
                paddingRight: '0',
                fontWeight: '600',
                textAlign: 'left',
                fontSize: '0.875rem',
                lineHeight: '1.25rem',
                color: 'hsl(var(--foreground))',
              },
              'tbody td': {
                borderBottomWidth: '1px',
                borderBottomColor: 'hsl(var(--border))',
                paddingBottom: '0.75rem',
                paddingTop: '0.75rem',
                paddingLeft: '0',
                paddingRight: '0',
                fontSize: '0.875rem',
                lineHeight: '1.25rem',
                color: 'hsl(var(--foreground))',
              },
              hr: {
                borderColor: 'hsl(var(--border))',
                marginTop: '3rem',
                marginBottom: '3rem',
              },
            },
          ],
        },
      }),
    },
  },
}

export default config
